version: '3.5'

networks:
  proxy:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy

  worker1:
    image: nginx
    container_name: worker1
    volumes:
      - ./worker1/default.conf:/etc/nginx/conf.d/default.conf
      - ./worker1/:/var/www/html
    networks:
      - proxy

  worker2:
    image: nginx
    container_name: worker2
    volumes:
      - ./worker2/default.conf:/etc/nginx/conf.d/default.conf
      - ./worker2/:/var/www/html
    networks:
      - proxy

